#!/bin/bash

set -e

usage="$(basename $0) <kernel-dir> <config-uri> <output-dir>"

if [[ $# -ne 3 ]]; then
	echo "${usage}" >&2
	exit 1
fi

KERNEL=$(realpath $1)
CONFIG=$2
if [[ ! "${CONFIG}" =~ ^https?:// ]]; then
	CONFIG=$(realpath $2)
fi
OUTPUT="$(realpath $3)"

docker run --network host \
	-v${KERNEL}:${KERNEL} \
	-v${OUTPUT}:${OUTPUT} \
	-it beshleman/makevm \
	${KERNEL} ${CONFIG} ${OUTPUT}
